Auth/urls.py
from django.urls import path
from django.contrib.auth import views as authLib
from . import views

app_name = 'Auth'

urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='nama'),
    path('signup/', views.signup, name='signup'),
    path('login/', authLib.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', authLib.LogoutView.as_view(template_name='logout.html', next_page=None), name='logout'),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.home, name='home'),
    path('query/', views.query_buku, name='query'),
    # path('test/', views.test, name='test'),
    # path('demo/', views.demo, name='demo')
]

story8/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('auth/', include('Auth.urls')),
]

main/models.py
from django.db import models

# Create your models here.

main/views.py
from django.shortcuts import render
from django.http import JsonResponse
from requests import get
import json


def home(request):
    return render(request, 'main/home.html')

def query_buku(request):
    keyword = request.GET['q']
    url = "https://www.googleapis.com/books/v1/volumes?q=" + keyword
    data = get(url).content
    data = json.loads(data)
    return JsonResponse(data, safe=False)

# def test(request):
#     return render(request,'main/tes.html')
#
# def demo(request):
#     return render(request, 'main/demo.html')

main/templates/main/demo.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script>
        $(document).ready(function () {
            $("button").click(function () {
                $("#div1").empty();
                $("#div1").append('loading...');
                $.ajax({
                    url: "https://my-json-server.typicode.com/jonathanfilbert/pti-api/data",
                    success: function (result) {
                        $("#div1").empty();
                        for (i = 0; i < result.anggota.length; i++) {
                            $("#div1").append(" <li> " + result.anggota[i].nama + "</li>");
                        }
                    }
                });
            });
        });
    </script>
</head>
<body>
<button>Load data</button>
<div id="div1">
<ul>

</ul>
</div>
</body>
</html>

main/templates/main/home.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}

<title>PPW Story 8</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<style>
    body {
        background-color: #e2e2e2;
        margin: 0;
        font-family: "Book Antiqua";
    }
    .judul{
        text-align: center;
        margin-bottom: 50px;
    }
    .container-utama {
        margin-left: 10%;
        margin-right: 10%;
        margin-top: 0.5rem;
        padding: 3rem;
    }

    .search-box {
        margin-bottom: 2rem;
        margin-right: 3rem;
    }

    #keyword {
        width: 100%;
        height: 2rem;
        font-size: 18px;
        border-radius: 5px;
        padding-left: 20px;
        padding-right: 20px;
    }
    #keyword:hover {
        color: white;
        background-color: #525252;
    }

    .buku{
        display: flex;
        justify-content: center;
        width: 100%;
    }

    table {
        width: 100%;
    }

    #tablebody td, #tablehead th {
        padding: 8px;
    }

    #tablehead tr {
        background-color: #4f4f4f;
        color: white;
    }
    #tablebody{
        background-color: whitesmoke;
        text-align: center;
    }
    #tablebody tr:hover {background-color: #525252 ;color: white}




</style>
{% endblock meta %}

{% block content %}
<div class="container-utama">
    <div class="judul">
        <h1>Daftar Buku</h1>
    </div>
    <div class="search-box">
        <input id="keyword" type="text" placeholder="Judul Buku...">
    </div>
    <div class="buku">
        <table>
            <thead id="tablehead">
            <tr>
                <th>
                    No
                </th>
                <th>
                    Photo
                </th>
                <th>
                    Title
                </th>
            </tr>
            </thead>
            <tbody id="tablebody">

            </tbody>
        </table>
    </div>
</div>

{% endblock content %}
{% block script %}
<script type="text/javascript">
    $(document).ready(function () {
        var url_default = "/query?q=frozen 2";
        var list_buku = $(".buku > table > tbody");
        $.ajax({
            url: url_default,
            success: function (buku) {
                for (let i = 0; i < buku.items.length; i++) {
                    var number = i+1;
                    var title = buku.items[i].volumeInfo.title;
                    var thumbnail = buku.items[i].volumeInfo.imageLinks.smallThumbnail;
                    list_buku.append(`<tr><td>${number}</td><td><img src=${thumbnail}></td><td>${title}</td></tr>`);
                }
            }
        })
    });

    $("#keyword").keyup(function () {
        var keyword = $("#keyword").val();
        var url_buku = "/query?q=" + keyword;
        $.ajax({
            url: url_buku,
            success: function (buku) {
                var list_buku = $(".buku > table > tbody");
                list_buku.empty();
                for (let i = 0; i < buku.items.length; i++) {
                    var number = i+1;
                    var title = buku.items[i].volumeInfo.title;
                    var thumbnail = buku.items[i].volumeInfo.imageLinks.smallThumbnail;
                    list_buku.append(`<tr><td>${number}</td><td><img src=${thumbnail}></td><td>${title}</td><</tr>`);
                }
            }
        })
    });
</script>

{% endblock script %}

main/templates/main/tes.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<title>tes</title>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
{% endblock meta %}

{% block content %}

<div id="div1"></div>

<button>Button</button>
{% endblock content %}
{% block script %}
<script type="text/javascript">
$(document).ready(function(){
  $("button").click(function(){
    $.ajax({url: "http://universities.hipolabs.com/search?country=Indonesia", success: function(result){
        for (i = 0; i < 10; i++){
         $("#div1").append( result[i].country + ", " + result[i].web_pages[0] +"<br>" ) ;
        }
    }});
  });
});
</script>
{% endblock script %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block meta %}
  {% endblock meta %}
</head>

<body>
  {% block content %}
  {% endblock content %}
</body>
{% block script %}
{% endblock script %}
</html>

templates/base1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    {% block meta %}
    {% endblock meta %}
</head>

<body>
{% block content %}
{% endblock content %}
</body>
{% block script %}
{% endblock script %}
</html>

templates/halo.html
{% extends 'base1.html' %}

{% load static %}

{% block meta %}
<title>Story 9</title>
{% endblock meta %}

{% block content %}

<div class="container option" style="width:300px; margin-top: 260px">
	{% if user.is_authenticated %}
    <a id="home" href="{% url 'Auth:nama' %}" type="button" class="btn btn-outline-primary btn-block">Home</a>
    <a id="logout" href="{% url 'Auth:logout' %}" type="button" class="btn btn-outline-danger btn-block">Log Out</a>
	{% else %}
	    <a id="login" href="{% url 'Auth:login' %}" type="button" class="btn btn-outline-success btn-block">Log In</a>
	    <a id="signup" href="{% url 'Auth:signup' %}" type="button" class="btn btn-outline-primary btn-block">Sign Up</a>
	{% endif %}
</div>

{% endblock %}

{% block script %}
{% endblock %}

templates/login.html
{% extends 'base1.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% block meta %}
{% endblock meta %}
{% block content %}
<div class="container login-body" style="width: 600px; margin-top: 150px">

    <div class="login-form">
        <form action="#" method="POST">
            {%csrf_token%}

            {{form|crispy}}
            <div >
                <button id="login-button" type="submit" class="btn btn-outline-success btn-block">Login</button>
            </div>
        </form>
        <small class="text-muted" style="margin-top: 10px;">
        Belum punya akun? <a class="ml-2" href="{% url 'Auth:signup' %}" style="">Sign up</a>
        </small>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}

templates/logout.html
{% extends 'base1.html' %}

{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container logout-body">

	<blockquote class="blockquote text-center">
	  <p class="mb-0" style="margin-top: 250px">Logged out!</p>
	</blockquote>

	<div class="container login-button" style="width: 300px">
		<form action="{% url 'Auth:login' %}">
		    <button id="login-button" type="submit" class="btn btn-outline-primary btn-block">Login Page</button>
		</form>
	</div>
</div>

{% endblock %}

{% block script %} 
{% endblock %}

templates/nama.html
{% extends 'base1.html' %}

{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container dashboard-body">
    {% if user.is_authenticated %}
    <blockquote class="blockquote text-center">
        <p class="mb-0" id="usernameP" style="margin-top: 250px">Selamat datang, {{user.username}}!</p>
    </blockquote>
	<div class="container" style="width: 300px">
		<a id="logout" href="{% url 'Auth:logout' %}" type="button" class="btn btn-outline-danger btn-block">Log Out</a>
	</div>
    {% endif %}
</div>

{% endblock %}

{% block script %}
{% endblock %}

templates/signup.html
{% extends 'base1.html' %}

{% load crispy_forms_tags %}
{% load static %}

{% block meta %}
{% endblock meta %}

{% block content %}

<div class="container signup-body" style="width: 600px; margin-top: 120px">

    <div class="signup-form">
        <form action="#" method="POST">
            {%csrf_token%}

            {{form|crispy}}
            <button id="signup-button" type="submit" class="btn btn-outline-success btn-block">Sign Up</button>
        </form>
        <small class="text-muted">
        sudah punya akun? <a class="ml-2" href="{% url 'Auth:login' %}">Login</a>
      </small>
    </div>


</div>

{% endblock %}

{% block script %}
{% endblock %}